permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

# See https://jekyllrb.com/docs/variables/
url: https://www.josephkirwin.com
title_image: https://www.josephkirwin.com/public/images/logo.jpg
baseurl:

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jemoji

sass:
  sass_dir: public/css
  style: :compressed

twitter_username: josephkirwin
github_username:  joekir 
linkedin_username: joekirwin
keybase_username: joekirwin

author:
  twitter: josephkirwin