markdown: kramdown
permalink: /:year/:month/:day/:title

kramdown:
  input: GFM
  syntax_highlighter: rouge

url: 
baseurl:

safe: True

sass:
  sass_dir: public/css
  style: :compressed

twitter_username: josephkirwin
github_username:  joekir 
linkedin_username: joekirwin 
