permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

url: https://www.josephkirwin.com
baseurl:

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji

sass:
  sass_dir: public/css
  style: :compressed

twitter_username: josephkirwin
github_username:  joekir 
linkedin_username: joekirwin
keybase_username: joekirwin
