markdown: kramdown
permalink: /:year/:month/:day/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

url: http://www.josephkirwin.com
baseurl:

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji

sass:
  sass_dir: public/css
  style: :compressed

twitter_username: josephkirwin
github_username:  joekir 
linkedin_username: joekirwin
keybase_username: joekirwin
