permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

# necessary for Twitter Card:
url: https://www.josephkirwin.com
description: A blog about Information Security and other ramblings.
title_image: https://www.josephkirwin.com/public/images/logo.jpg
mastodon_username: '@joek@infosec.exchange'

baseurl:

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jemoji

sass:
  sass_dir: public/css
  style: :compressed

github_username:  joekir 
linkedin_username: joekirwin
keybase_username: joekirwin